import { redirect } from "next/navigation";
import { Activity, Cpu, Database, Radio } from "lucide-react";
import { getAdminUser } from "@/shared/lib/admin";
import { sqlite } from "@/shared/lib/sqlite/db";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export default async function AdminMonitoringPage() {
  const user = await getAdminUser();
  if (!user) redirect("/dashboard");
  const devices = sqlite.prepare("SELECT device_code, name, status, battery_level, last_ping FROM iot_sensor_devices ORDER BY last_ping DESC LIMIT 10").all() as Array<{ device_code: string; name: string | null; status: string; battery_level: number | null; last_ping: string | null }>;
  const readings = sqlite.prepare("SELECT COUNT(*) as count FROM water_quality_readings").get() as { count: number };
  const online = sqlite.prepare("SELECT COUNT(*) as count FROM iot_sensor_devices WHERE status = 'online'").get() as { count: number };
  const sessions = sqlite.prepare("SELECT COUNT(*) as count FROM sessions WHERE expires_at > CURRENT_TIMESTAMP").get() as { count: number };
  const metrics = [{ label: "Sensor online", value: online.count, icon: Radio }, { label: "Pembacaan tersimpan", value: readings.count, icon: Activity }, { label: "Sesi aktif", value: sessions.count, icon: Cpu }];
  return <div className="mx-auto max-w-6xl space-y-8"><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.14em] text-sky-600">Administration</p><h1 className="text-2xl font-semibold tracking-tight">Monitoring</h1><p className="mt-1 text-sm text-muted-foreground">Kondisi perangkat IoT dan aktivitas instance PondFlow.</p></div><div className="grid gap-3 md:grid-cols-3">{metrics.map(({ label, value, icon: Icon }) => <div key={label} className="flex items-center gap-4 rounded-xl bg-white px-5 py-4 shadow-sm dark:bg-slate-900"><Icon className="h-5 w-5 text-sky-600" strokeWidth={1.8} /><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div></div>)}</div><section className="overflow-hidden rounded-xl bg-white shadow-sm dark:bg-slate-900"><div className="flex items-center gap-3 p-5"><Database className="h-5 w-5 text-slate-500" /><div><h2 className="font-semibold">Perangkat sensor</h2><p className="mt-1 text-sm text-muted-foreground">Sepuluh perangkat terakhir berdasarkan ping.</p></div></div><Table className="min-w-[620px]"><TableHeader><TableRow className="bg-slate-50/80 hover:bg-slate-50/80 dark:bg-slate-950/50 dark:hover:bg-slate-950/50"><TableHead>Perangkat</TableHead><TableHead>Status</TableHead><TableHead>Baterai</TableHead><TableHead>Ping terakhir</TableHead></TableRow></TableHeader><TableBody>{devices.map((device) => <TableRow key={device.device_code}><TableCell><p className="font-medium">{device.name || "Unnamed sensor"}</p><p className="text-xs text-muted-foreground">{device.device_code}</p></TableCell><TableCell><span className={device.status === "online" ? "text-emerald-600" : "text-slate-500"}>{device.status}</span></TableCell><TableCell>{device.battery_level == null ? "—" : `${device.battery_level}%`}</TableCell><TableCell className="text-muted-foreground">{device.last_ping ? new Date(device.last_ping).toLocaleString("id-ID") : "—"}</TableCell></TableRow>)}</TableBody></Table>{devices.length === 0 && <p className="px-5 py-8 text-center text-sm text-muted-foreground">Belum ada perangkat sensor.</p>}</section></div>;
}
