import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, ArrowRight, BarChart3, Bell, CircleDollarSign, Droplets, Fish, Gauge, Leaf, MoreHorizontal, Sparkles, WalletCards } from "lucide-react";

export const metadata = {
  title: "Demo Dashboard",
  description: "Lihat contoh dashboard operasional PondFlow.",
};

const expenses = [
  ["Pakan pelet 781", "Pakan", "Rp 1.850.000", "text-amber-600 bg-amber-50"],
  ["Benih nila 2.000 ekor", "Benih", "Rp 900.000", "text-cyan-600 bg-cyan-50"],
  ["Listrik & aerasi", "Operasional", "Rp 350.000", "text-violet-600 bg-violet-50"],
];

export default function DemoPage() {
  return (
    <main className="min-h-screen bg-[#f4f8fa] text-slate-900">
      <header className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10">
          <Link href="/" className="flex items-center gap-3 text-sm font-extrabold"><Image src="/logo.png" alt="PondFlow" width={36} height={36} className="rounded-xl" priority /><span>Pond<span className="text-teal-600">Flow</span> <span className="ml-1 rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-slate-500">Demo</span></span></Link>
          <div className="flex items-center gap-3"><Link href="/" className="hidden items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-slate-900 sm:flex"><ArrowLeft size={16} /> Kembali</Link><Link href="/register" className="rounded-full bg-[#092b3c] px-4 py-2.5 text-sm font-bold text-white transition hover:bg-[#123f54]">Mulai gratis</Link></div>
        </div>
      </header>

      <section className="mx-auto max-w-7xl px-6 pb-8 pt-10 lg:px-10 lg:pt-14"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-teal-600">Contoh workspace</p><h1 className="mt-3 text-4xl font-black tracking-[-.04em] text-slate-950 sm:text-5xl">Ringkasan operasional</h1><p className="mt-3 max-w-xl text-slate-500">Contoh tampilan PondFlow untuk membantu Anda melihat kondisi usaha dalam satu pandangan.</p></div><div className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-500"><span className="h-2 w-2 rounded-full bg-emerald-500" /> Data contoh · Mei 2026</div></div></section>

      <section className="mx-auto max-w-7xl px-6 pb-16 lg:px-10"><div className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-xl shadow-slate-200/60 sm:p-6"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-slate-400">Selamat datang kembali</p><h2 className="mt-1 text-xl font-extrabold">Halo, Kinas 👋</h2></div><div className="flex items-center gap-3"><button className="rounded-xl border border-slate-200 p-2.5 text-slate-500"><Bell size={17} /></button><div className="flex h-9 w-9 items-center justify-center rounded-full bg-teal-100 text-sm font-extrabold text-teal-700">K</div></div></div>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl bg-[#e2f8f2] p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">Pendapatan bulan ini</p><WalletCards size={18} className="text-teal-600" /></div><p className="mt-4 text-2xl font-black text-teal-950">Rp 24,8 jt</p><p className="mt-2 text-xs font-semibold text-teal-700">↑ 18,4% dari bulan lalu</p></div><div className="rounded-2xl bg-[#e6f1ff] p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Total biaya</p><CircleDollarSign size={18} className="text-blue-600" /></div><p className="mt-4 text-2xl font-black text-blue-950">Rp 16,4 jt</p><p className="mt-2 text-xs font-semibold text-blue-700">Dalam 3 siklus aktif</p></div><div className="rounded-2xl bg-[#fff4d9] p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wide text-amber-700">Kolam aktif</p><Fish size={18} className="text-amber-600" /></div><p className="mt-4 text-2xl font-black text-amber-950">12 <span className="text-sm">kolam</span></p><p className="mt-2 text-xs font-semibold text-amber-700">4 lokasi budidaya</p></div><div className="rounded-2xl bg-[#f0eaff] p-5"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wide text-violet-700">Rata-rata FCR</p><Gauge size={18} className="text-violet-600" /></div><p className="mt-4 text-2xl font-black text-violet-950">1,42</p><p className="mt-2 text-xs font-semibold text-violet-700">Efisiensi pakan bagus</p></div></div>

          <div className="mt-4 grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.13em] text-slate-400">Performa pendapatan vs biaya</p><p className="mt-1 font-extrabold">Tren 6 bulan terakhir</p></div><BarChart3 className="text-teal-600" size={20} /></div><div className="mt-8 flex h-44 items-end gap-3 border-b border-l border-slate-200 px-3 pb-0 sm:gap-6"><div className="relative flex h-full flex-1 items-end gap-1"><span className="h-[38%] w-1/2 rounded-t bg-slate-200" /><span className="h-[54%] w-1/2 rounded-t bg-teal-300" /></div><div className="relative flex h-full flex-1 items-end gap-1"><span className="h-[46%] w-1/2 rounded-t bg-slate-200" /><span className="h-[62%] w-1/2 rounded-t bg-teal-300" /></div><div className="relative flex h-full flex-1 items-end gap-1"><span className="h-[42%] w-1/2 rounded-t bg-slate-200" /><span className="h-[58%] w-1/2 rounded-t bg-teal-300" /></div><div className="relative flex h-full flex-1 items-end gap-1"><span className="h-[59%] w-1/2 rounded-t bg-slate-200" /><span className="h-[70%] w-1/2 rounded-t bg-teal-300" /></div><div className="relative flex h-full flex-1 items-end gap-1"><span className="h-[55%] w-1/2 rounded-t bg-slate-200" /><span className="h-[79%] w-1/2 rounded-t bg-teal-300" /></div><div className="relative flex h-full flex-1 items-end gap-1"><span className="h-[64%] w-1/2 rounded-t bg-slate-200" /><span className="h-[91%] w-1/2 rounded-t bg-teal-600" /></div></div><div className="mt-3 flex justify-between pl-3 text-[10px] font-semibold text-slate-400"><span>Des</span><span>Jan</span><span>Feb</span><span>Mar</span><span>Apr</span><span>Mei</span></div><div className="mt-5 flex gap-5 text-xs font-semibold text-slate-500"><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-slate-300" /> Biaya</span><span className="flex items-center gap-2"><i className="h-2 w-2 rounded-full bg-teal-500" /> Pendapatan</span></div></div><div className="rounded-2xl bg-[#092b3c] p-5 text-white"><div className="flex items-center gap-2 text-cyan-300"><Sparkles size={18} /><p className="text-xs font-extrabold uppercase tracking-[.14em]">AI Insight</p></div><h3 className="mt-5 text-lg font-extrabold">Siklus berjalan cukup sehat</h3><p className="mt-3 text-sm leading-6 text-slate-300">FCR 1,42 berada di rentang bagus. Biaya pakan menyumbang 58% dari total biaya produksi.</p><div className="mt-6 rounded-xl bg-white/10 p-3 text-xs font-semibold leading-5 text-cyan-100">Rekomendasi: pertahankan frekuensi pakan dan evaluasi harga supplier pada siklus berikutnya.</div></div></div>

          <div className="mt-4 grid gap-4 lg:grid-cols-[.9fr_1.1fr]"><div className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.13em] text-slate-400">Siklus aktif</p><p className="mt-1 font-extrabold">Progress budidaya</p></div><Droplets className="text-cyan-600" size={20} /></div><div className="mt-5 space-y-4"><div><div className="flex justify-between text-xs font-bold"><span>Nila A-03</span><span className="text-teal-600">72%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 w-[72%] rounded-full bg-teal-500" /></div></div><div><div className="flex justify-between text-xs font-bold"><span>Lele B-01</span><span className="text-cyan-600">48%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 w-[48%] rounded-full bg-cyan-500" /></div></div><div><div className="flex justify-between text-xs font-bold"><span>Gurame C-02</span><span className="text-amber-600">31%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 w-[31%] rounded-full bg-amber-400" /></div></div></div></div><div className="rounded-2xl border border-slate-200 p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.13em] text-slate-400">Pengeluaran terbaru</p><p className="mt-1 font-extrabold">Aktivitas keuangan</p></div><MoreHorizontal className="text-slate-400" size={20} /></div><div className="mt-3 divide-y divide-slate-100">{expenses.map(([name, category, amount, color]) => <div key={name} className="flex items-center justify-between py-3"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${color}`}><CircleDollarSign size={16} /></span><div><p className="text-sm font-bold">{name}</p><p className="text-xs text-slate-400">{category}</p></div></div><p className="text-sm font-extrabold">{amount}</p></div>)}</div></div></div>
        </div></section>

      <section className="bg-[#092b3c] px-6 py-16 text-white"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 sm:flex-row sm:items-center lg:px-10"><div><p className="text-sm font-extrabold uppercase tracking-[.16em] text-cyan-300">Ini baru contoh kecilnya</p><h2 className="mt-3 text-3xl font-black tracking-tight">Siap mengelola budidaya dengan lebih terukur?</h2></div><Link href="/register" className="inline-flex items-center gap-2 rounded-full bg-cyan-300 px-6 py-3.5 text-sm font-extrabold text-[#082234] transition hover:bg-cyan-200">Mulai gratis <ArrowRight size={17} /></Link></div></section>
    </main>
  );
}
